name: API Tests (Manual + Scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Save run time
        id: get-time
        run: echo "time=$(date '+%d.%m.%Y %H:%M')" >> "$GITHUB_OUTPUT"

      - name: Generate api.properties from secrets
        run: |
          mkdir -p src/test/resources
          echo "api.baseUri=${{ secrets.API_BASE_URI }}" > src/test/resources/api.properties
          echo "api.basePath=${{ secrets.API_BASE_PATH }}" >> src/test/resources/api.properties
          echo "api.key=${{ secrets.API_KEY }}" >> src/test/resources/api.properties

      - name: Run tests
        run: ./gradlew clean test
        continue-on-error: true

      - name: Generate Allure report
        run: ./gradlew allureReport

      - name: Debug â€” ÐµÑÑ‚ÑŒ Ð»Ð¸ Ñ€ÐµÐ·ÑƒÐ»ÑŒÑ‚Ð°Ñ‚Ñ‹ Ñ‚ÐµÑÑ‚Ð¾Ð²
        run: |
          echo "ðŸ” Ð¡Ð¼Ð¾Ñ‚Ñ€Ð¸Ð¼ build/allure-results:"
          ls -l build/allure-results


      - name: Archive Allure report (correct structure)
        run: |
         cd build/reports/allure-report/allureReport
         zip -r ../../../../allure-report.zip ./*

      - name: Upload zipped Allure report
        uses: actions/upload-artifact@v4
        with:
         name: allure-report
         path: build/allure-report.zip


      - name: Generate donut chart from Allure summary
        run: node generateChart.js

      - name: Create Telegram message
        id: generate-message
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          TIME: ${{ steps.get-time.outputs.time }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          node generateMessage.js > message.txt

      - name: Send chart and message to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendPhoto" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F photo=@"allure-summary-chart.png" \
            -F caption="$(cat message.txt)" \
            -F parse_mode="Markdown"


